### ISSUE TITLE
How to set Configuration#* of Selenide correctly?

### ISSUE THREAD

**Issue by ansonliao** [ansonliao/Selenium-RottenTomatoes#1]
Hi @asolntsev
Please kindly check this repo's latest code of the branch master, 
1. 
I set the timeout via the code `Configuration.timeout = 10000;` to 10 seconds, but looks like it doesn't work, please check the test output screenshot:
![image](https://user-images.githubusercontent.com/6060224/90037193-7cad0200-dcf6-11ea-87e5-d80bd3ecc2b1.png)

And my test script is very simple and straightforward without any PO pattern.
![image](https://user-images.githubusercontent.com/6060224/90037325-ab2add00-dcf6-11ea-98d7-9e243834825e.png)

2. 
When you execute the test by the specified group of TestNG: ` ./gradlew clean debug`, as the custom webdriver provider is set the chrome browser to mobile emulation, but when running this one, the mobile emulation is out of work.

![image](https://user-images.githubusercontent.com/6060224/90043234-6d31b700-dcfe-11ea-8979-46d3ee66524b.png)

![image](https://user-images.githubusercontent.com/6060224/90043076-25129480-dcfe-11ea-8219-057b55579a0c.png)

I would like to consult you that how can I set the configuration of Selenide correctly, thanks.

**Comment by asolntsev** [comment]
@ansonliao Hi.
1. You set Selenide `Configuration` (almost) correctly. 
  1.1. "almost" means that I recommend moving `Configuration.timeout = 10000` from `SelenideWebDriverProvider` to `GoogleTest`. It's not a responsibility of `WebDriverProvider` to set timeout (or any other settings).`WebDriverProvider` is only responsible for opening a browser.
  1.2. As a consequence, you log the timeout BEFORE opening the browser. At that moment `SelenideWebDriverProvider` is not called yet, and the timeout is still 4000.
2. What is actually wrong is TestNG usage. When you run TestNG with flag `includeGroups 'debug'`, it does NOT run `@BeforeMethod` (**WTF, TestNG!**). 
  2.1. One possible solution is to write `@BeforeMethod(alwaysRun = true)`. See [explanation](https://stackoverflow.com/questions/5020260/testng-beforemethod-method-not-called-when-it-resides-in-superclass-and-a-speci).

**Comment by ansonliao** [comment]
@asolntsev 
Thanks so much.
1.
I moved `Configuration` from custom webdriver provider to `@Before#` of `TestNG`, also call the setting of `Configuration` after `Configuration.brower=xxxx`, it works fine.

2. 
`alwaysRun = true` solved many problems I met, sometimes with `Allure-Selenide` library, no screenshot attached to Allure report when the test case failed, after set ` alwaysRun = true` solved the problem, also includes the custom browser capabilities.

Thanks so much.
